### ISSUE TITLE
Safemath everywhere

### ISSUE THREAD

**Issue by karimodm** [iotaledger/iota-core#223]
- use addition whenever possible
- when it makes sense compute with safemath
- don't panic, always return ierrors across the code
```[tasklist]
### Tasks
- [x] `pkg/core/account/accounts.go`
- [x] `pkg/protocol/engine/accounts/accountsledger/manager.go`
- [x] `pkg/protocol/engine/congestioncontrol/scheduler/drr/scheduler.go`
```
