### ISSUE TITLE
Harmonize serialization utils, methods on objects and more

### ISSUE THREAD

**Issue by jonastheis** [iotaledger/iota-core#284]
```[tasklist]
### Tasks
- [x] Currently we have and use multiple tools for serialization throughout the code base. We're using everything except `marshalutil` heavily. Therefore, we should try to remove dependencies to `marshalutil` to decrease the amount of code and thus error surface.
- [x] Go away from manual `binary.Read` and `binary.Write` in favor of utils provided in `stream` package
- [x] Remove objects' `.FromBytes()` method in favor of stateless `ObjectFromBytes()` function to avoid quirks with Go generics
- [x] Remove `storable` package from hive.go
- [x] Remove `PositionedWriter` and replace with `stream.WriteCollection`
- [x] introduce/generate wrapper to conveniently store basic types with our `kvstore.TypedKVStore`
- [x] Revisit `time.Time` serialization (seconds vs nanoseconds)
- [x] Introduce better way to serialize and deserialize `BlockIssuerKeys`
```

**Comment by jonastheis** [comment]
In [this commit](https://github.com/iotaledger/iota.go/commit/b61e53dbf4890fe5a9ea7606fe6e4d6904eba9ce ) the serialization of `BlockIssuerKeys` has been improved. However, it showcases one problem well:
- many objects can be read/written in the context of a `reader` (e.g. for a snapshot). While the total object size might be variable, the object is still able to deserialize itself without the need to always prepend a size (just by following the order and reading the individual fields from the reader). This becomes important when we are writing lots of objects, for example outputs, for a ledger state snapshot. 
- When and how exactly do we utilize `serix`? Some objects are sometimes serialized with `serix` but other times not. Especially when reading from a `reader` currently `serix` does not support that.
