### ISSUE TITLE
Adapt INX-Indexer to newest nova VM

### ISSUE THREAD

**Issue by alexsporn** [iotaledger/iota-core#410]
```[tasklist]
### Tasks
- [ ] Add support for AnchorOutputs
- [x] Adapt NativeTokens and make them queryable
- [ ] Check if we can do some easy balance calculations
- [x] Check data types (SlotIndex 32bit, payload type 8bit etc)
- [x] Add unit-tests to verify indexer is properly indexing stuff
```
