### ISSUE TITLE
SegWit: calculate, store and retrieve Outputs proofs

### ISSUE THREAD

**Issue by karimodm** [iotaledger/iota-core#412]
```[tasklist]
### Tasks
- [x] Store outputs proof in output metadata for each unspent output.
- [x] Change client interaction to retrieve output metadata from API to verify proofs.
- [x] Change TX ID calculation as H(TransactionCommitment + OutputMerkleRoot)
```
