### ISSUE TITLE
Add a GenesisSlot parameter to the protocol

### ISSUE THREAD

**Issue by alexsporn** [iotaledger/iota-core#431]
We should be able to bootstrap a network with a genesis slot different than 0.
This allows us to e.g. migrate Shimmer and IOTA and keep the old milestone indexes to have a coherent tangle history.
```[tasklist]
### Tasks
- [x] Add GenesisSlot parameter to the ProtocolParameters
- [x] Use the GenesisSlot in the TimeProvider
- [x] Adapt all special cases of 0 as genesis to use GenesisSlot instead
```
