### ISSUE TITLE
Implement core REST API

### ISSUE THREAD

**Issue by jonastheis** [iotaledger/iota-core#50]
Many of the APIs are implemented in #72 

```[tasklist]
### TODOs
- [x] control APIs
- [x] peers APIs
- [x] blockReason, TxState, TxReason in BlockMetadata
- [x] CommitmentIDSpent, TransactionIDSpent in OutputMetadata
- [x] pruningSlot, baseToken in `/info`
- [x] accounts retrieval
- [x] review Swagger file
- [x] Implement health check
- [x] Finish congestion api (scheduler)
- [x] rewards api: epoch should be returned by the reward calculations
- [x] pagination for stakers endpoint
- [ ] Finish congestion: RMC
- [ ] extra fields to add to CommitmentResponse: RMC
- [ ] Finish staking api (supported protocol version of each validator)
- [ ] finish  `checkUpcomingUnsupportedProtocolVersion`
- [ ] In `responseByHeader`, encode object with its api version
- [ ] add performance factor to committee response
- [ ] does event API needs any updates
```
